/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Option } from "./utils/models";
export { Option } from "./utils/models";
export namespace Components {
    /**
     * Custom dropdown component with built in optional search. Should be used along with custom-option components simiarly
     * to the native browser select element
     */
    interface CustomDropdown {
        /**
          * Label above the dropdown
         */
        "label": string;
    }
    /**
     * Custom option element for use with the custom-dropdown element. Acts similarly to the browser's
     * built in option element. Only to be used inside of custom-dropdown
     */
    interface CustomOption {
        /**
          * The value that will emitted when the custom-dropdown changes
         */
        "value": string;
    }
}
export interface CustomDropdownCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCustomDropdownElement;
}
export interface CustomOptionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLCustomOptionElement;
}
declare global {
    interface HTMLCustomDropdownElementEventMap {
        "changeDropdown": string;
    }
    /**
     * Custom dropdown component with built in optional search. Should be used along with custom-option components simiarly
     * to the native browser select element
     */
    interface HTMLCustomDropdownElement extends Components.CustomDropdown, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCustomDropdownElementEventMap>(type: K, listener: (this: HTMLCustomDropdownElement, ev: CustomDropdownCustomEvent<HTMLCustomDropdownElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCustomDropdownElementEventMap>(type: K, listener: (this: HTMLCustomDropdownElement, ev: CustomDropdownCustomEvent<HTMLCustomDropdownElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCustomDropdownElement: {
        prototype: HTMLCustomDropdownElement;
        new (): HTMLCustomDropdownElement;
    };
    interface HTMLCustomOptionElementEventMap {
        "selectOption": Option;
    }
    /**
     * Custom option element for use with the custom-dropdown element. Acts similarly to the browser's
     * built in option element. Only to be used inside of custom-dropdown
     */
    interface HTMLCustomOptionElement extends Components.CustomOption, HTMLStencilElement {
        addEventListener<K extends keyof HTMLCustomOptionElementEventMap>(type: K, listener: (this: HTMLCustomOptionElement, ev: CustomOptionCustomEvent<HTMLCustomOptionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLCustomOptionElementEventMap>(type: K, listener: (this: HTMLCustomOptionElement, ev: CustomOptionCustomEvent<HTMLCustomOptionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLCustomOptionElement: {
        prototype: HTMLCustomOptionElement;
        new (): HTMLCustomOptionElement;
    };
    interface HTMLElementTagNameMap {
        "custom-dropdown": HTMLCustomDropdownElement;
        "custom-option": HTMLCustomOptionElement;
    }
}
declare namespace LocalJSX {
    /**
     * Custom dropdown component with built in optional search. Should be used along with custom-option components simiarly
     * to the native browser select element
     */
    interface CustomDropdown {
        /**
          * Label above the dropdown
         */
        "label"?: string;
        /**
          * Fires whenever the value of the dropdown changes
         */
        "onChangeDropdown"?: (event: CustomDropdownCustomEvent<string>) => void;
    }
    /**
     * Custom option element for use with the custom-dropdown element. Acts similarly to the browser's
     * built in option element. Only to be used inside of custom-dropdown
     */
    interface CustomOption {
        /**
          * Fired when clicking on an option
         */
        "onSelectOption"?: (event: CustomOptionCustomEvent<Option>) => void;
        /**
          * The value that will emitted when the custom-dropdown changes
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "custom-dropdown": CustomDropdown;
        "custom-option": CustomOption;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Custom dropdown component with built in optional search. Should be used along with custom-option components simiarly
             * to the native browser select element
             */
            "custom-dropdown": LocalJSX.CustomDropdown & JSXBase.HTMLAttributes<HTMLCustomDropdownElement>;
            /**
             * Custom option element for use with the custom-dropdown element. Acts similarly to the browser's
             * built in option element. Only to be used inside of custom-dropdown
             */
            "custom-option": LocalJSX.CustomOption & JSXBase.HTMLAttributes<HTMLCustomOptionElement>;
        }
    }
}
